[build]
  command = "bash netlify/build.sh"
  functions = "netlify/functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  included_files = ["prisma/schema.prisma", "prisma/migrations/**", "node_modules/.prisma/**"]
  external_node_modules = [
    "@prisma/client",
    "prisma",
    "@nestjs/microservices",
    "@nestjs/websockets",
    "class-transformer"
  ]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[dev]
  command = "npm run start:dev"
  port = 4000
  targetPort = 4000
  publish = "dist"

[environment]
  NODE_ENV = "production"